/* ---------- Mock SA tender data ---------- */
const TENDERS = [
  {
    id: "RFB 2025/IT/0142",
    title: "Supply, Delivery & Maintenance of Cybersecurity Infrastructure",
    issuer: "South African Revenue Service (SARS)",
    type: "Government · IT",
    value: "R 24,500,000",
    deadline: "2026-06-12",
    closingDays: 19,
    bbbeeRequired: "Level 2 or higher",
    score: 86,
    risk: "low",
    status: "in-review",
    province: "Gauteng",
    cidb: null,
    documents: 14,
    pages: 187,
    publishedDate: "2026-05-02",
    tags: ["NIST 800-53", "5-year contract", "On-site support"],
  },
  {
    id: "MUN/JHB/SEC/2026/008",
    title: "Provision of Physical Security Services at Municipal Depots",
    issuer: "City of Johannesburg Metropolitan",
    type: "Municipal · Security",
    value: "R 8,200,000",
    deadline: "2026-06-04",
    closingDays: 11,
    bbbeeRequired: "Level 1",
    score: 72,
    risk: "medium",
    status: "draft",
    province: "Gauteng",
    cidb: null,
    documents: 9,
    pages: 96,
    publishedDate: "2026-04-28",
    tags: ["PSIRA registered", "24/7 coverage", "Armed response"],
  },
  {
    id: "DPWI/CON/0421/26",
    title: "Construction of Mthatha District Office — Phase 2",
    issuer: "Dept. of Public Works & Infrastructure",
    type: "Government · Construction",
    value: "R 142,000,000",
    deadline: "2026-07-18",
    closingDays: 55,
    bbbeeRequired: "Level 1",
    score: 41,
    risk: "high",
    status: "flagged",
    province: "Eastern Cape",
    cidb: "8GB PE",
    documents: 22,
    pages: 312,
    publishedDate: "2026-05-08",
    tags: ["JBCC 2018", "CIDB 8GB", "BEP required"],
  },
  {
    id: "ESKOM/RFQ/2026/0337",
    title: "Maintenance of SCADA Systems — Northern Region",
    issuer: "Eskom Holdings SOC",
    type: "SOE · Engineering",
    value: "R 11,800,000",
    deadline: "2026-05-29",
    closingDays: 5,
    bbbeeRequired: "Level 4 or higher",
    score: 78,
    risk: "low",
    status: "in-review",
    province: "Limpopo",
    cidb: null,
    documents: 11,
    pages: 124,
    publishedDate: "2026-04-30",
    tags: ["ICS/SCADA", "Mandatory site visit", "OEM cert"],
  },
  {
    id: "WC/DOH/0218/26",
    title: "Cleaning & Hygiene Services — Tygerberg Hospital",
    issuer: "Western Cape Dept. of Health",
    type: "Provincial · Services",
    value: "R 6,400,000",
    deadline: "2026-06-21",
    closingDays: 28,
    bbbeeRequired: "Level 2",
    score: 91,
    risk: "low",
    status: "shortlisted",
    province: "Western Cape",
    cidb: null,
    documents: 8,
    pages: 71,
    publishedDate: "2026-05-12",
    tags: ["3-year contract", "OHSA compliant"],
  },
  {
    id: "TRANSNET/IT/2026/099",
    title: "Cloud Migration & SAP HANA Modernisation",
    issuer: "Transnet SOC Ltd",
    type: "SOE · IT",
    value: "R 58,000,000",
    deadline: "2026-08-02",
    closingDays: 70,
    bbbeeRequired: "Level 2",
    score: 63,
    risk: "medium",
    status: "draft",
    province: "KwaZulu-Natal",
    cidb: null,
    documents: 18,
    pages: 246,
    publishedDate: "2026-05-18",
    tags: ["Azure", "ISO 27001", "Skills transfer"],
  },
];

const COMPLIANCE_DOCS = [
  { id: "csd", category: "CSD", name: "CSD Registration Report", status: "valid", expires: "2026-11-04", uploaded: "2026-02-11", size: "412 KB", aiVerified: true, vendor: "MAAA0451729" },
  { id: "tcs", category: "Tax", name: "Tax Compliance Status (TCS) PIN", status: "valid", expires: "2026-08-22", uploaded: "2026-02-22", size: "118 KB", aiVerified: true, vendor: "TCS9817-3204-1126" },
  { id: "bbbee", category: "B-BBEE", name: "B-BBEE Affidavit (EME) — Level 2", status: "expiring", expires: "2026-06-08", uploaded: "2025-06-08", size: "284 KB", aiVerified: true, vendor: "EME · Sworn" },
  { id: "cipc", category: "CIPC", name: "CIPC Company Disclosure (CoR 14.3)", status: "valid", expires: null, uploaded: "2026-01-19", size: "640 KB", aiVerified: true, vendor: "2019/487112/07" },
  { id: "ins", category: "Insurance", name: "Public Liability Insurance — R10m", status: "valid", expires: "2027-03-31", uploaded: "2026-04-01", size: "1.2 MB", aiVerified: true, vendor: "Hollard · POL/2026/887" },
  { id: "bank", category: "Bank Letter", name: "Bank Confirmation — FNB Business", status: "expired", expires: "2026-04-30", uploaded: "2025-10-30", size: "92 KB", aiVerified: false, vendor: "62849173210" },
  { id: "sbd4", category: "SBD Forms", name: "SBD 4 — Declaration of Interest", status: "missing", expires: null, uploaded: null, size: null, aiVerified: false, vendor: null },
  { id: "sbd61", category: "SBD Forms", name: "SBD 6.1 — Preference Points Claim", status: "valid", expires: null, uploaded: "2026-03-04", size: "76 KB", aiVerified: true, vendor: null },
  { id: "letter", category: "Capability", name: "Capability Statement — Cybersecurity", status: "valid", expires: null, uploaded: "2026-04-22", size: "3.4 MB", aiVerified: true, vendor: "v4.2" },
  { id: "uif", category: "Tax", name: "UIF Compliance Letter", status: "valid", expires: "2026-09-15", uploaded: "2026-03-15", size: "104 KB", aiVerified: true, vendor: "U090332771" },
  { id: "coid", category: "Insurance", name: "Letter of Good Standing — COID", status: "expiring", expires: "2026-06-18", uploaded: "2025-06-18", size: "186 KB", aiVerified: true, vendor: "COID-2025/41773" },
];

const ACTIVITY = [
  { t: "2 min ago", who: "AI", text: "Identified 4 missing documents for SARS/IT/0142", icon: "alert" },
  { t: "18 min ago", who: "Lerato M.", text: "Uploaded revised pricing schedule (v3)", icon: "upload" },
  { t: "1 h ago", who: "AI", text: "Drafted executive summary for Eskom SCADA bid", icon: "sparkles" },
  { t: "3 h ago", who: "Sipho N.", text: "Approved compliance checklist", icon: "check" },
  { t: "Yesterday", who: "AI", text: "Tender RFB 2025/IT/0142 scored 86 (high match)", icon: "score" },
  { t: "Yesterday", who: "Thandi K.", text: "Added Capability Statement v4.2", icon: "doc" },
];

const CHAT_HISTORY = [
  { id: "c1", title: "SARS Cybersecurity — eligibility", date: "Today", active: true },
  { id: "c2", title: "Mthatha construction — risks", date: "Today" },
  { id: "c3", title: "Eskom SCADA — pricing breakdown", date: "Yesterday" },
  { id: "c4", title: "Tygerberg cleaning — staffing model", date: "Yesterday" },
  { id: "c5", title: "Transnet SAP — partnership requirements", date: "May 21" },
  { id: "c6", title: "B-BBEE level 2 vs level 1 implications", date: "May 18" },
];

const TENDER_REQUIREMENTS = [
  { id: "r1", section: "3.1", text: "Bidder must be registered on the Central Supplier Database (CSD)", status: "pass", page: 14 },
  { id: "r2", section: "3.2", text: "Valid Tax Compliance Status PIN issued within last 12 months", status: "pass", page: 14 },
  { id: "r3", section: "3.3", text: "B-BBEE Verification Certificate (Level 2 or higher)", status: "pass", page: 15 },
  { id: "r4", section: "3.4", text: "Minimum 5 years' experience in SOC operations for public sector", status: "warn", page: 16, note: "Submitted 4y 8m — request waiver" },
  { id: "r5", section: "3.5", text: "ISO 27001:2022 certification (valid)", status: "pass", page: 16 },
  { id: "r6", section: "3.6", text: "Local SOC facility in Gauteng with redundancy site", status: "pass", page: 17 },
  { id: "r7", section: "3.7", text: "At least 3 references for SARS-equivalent revenue authorities", status: "fail", page: 18, note: "Only 1 reference provided; need 2 more" },
  { id: "r8", section: "3.8", text: "OEM-certified personnel: Cisco, Palo Alto, CrowdStrike", status: "warn", page: 19, note: "Missing CrowdStrike Falcon certification" },
  { id: "r9", section: "3.9", text: "Tax-clearance for all directors (≥20% shareholding)", status: "pass", page: 20 },
  { id: "r10", section: "3.10", text: "PSIRA registration for on-site personnel", status: "pass", page: 21 },
];

const EVAL_CRITERIA = [
  { name: "Functionality / Technical", weight: 60, score: 52 },
  { name: "Price (90/10 PPPFA)", weight: 30, score: 27 },
  { name: "Preference Points (B-BBEE)", weight: 10, score: 8 },
];

const TENDER_ACTIVITY_MONTH = [
  { m: "Dec", uploaded: 3, won: 1, lost: 2 },
  { m: "Jan", uploaded: 6, won: 2, lost: 2 },
  { m: "Feb", uploaded: 8, won: 3, lost: 3 },
  { m: "Mar", uploaded: 7, won: 3, lost: 2 },
  { m: "Apr", uploaded: 11, won: 5, lost: 3 },
  { m: "May", uploaded: 14, won: 6, lost: 4 },
];

const PROPOSAL_SECTIONS = [
  { id: "ps1", title: "Cover Letter", words: 312, status: "approved", lastEdit: "8 min ago" },
  { id: "ps2", title: "Executive Summary", words: 786, status: "ai-draft", lastEdit: "just now" },
  { id: "ps3", title: "Company Background", words: 540, status: "approved", lastEdit: "2 h ago" },
  { id: "ps4", title: "Technical Methodology", words: 2140, status: "in-review", lastEdit: "1 h ago" },
  { id: "ps5", title: "Compliance Matrix", words: 0, status: "auto", lastEdit: "auto-generated" },
  { id: "ps6", title: "Pricing Schedule", words: 184, status: "draft", lastEdit: "yesterday" },
  { id: "ps7", title: "References & Case Studies", words: 612, status: "approved", lastEdit: "yesterday" },
  { id: "ps8", title: "Submission Checklist", words: 0, status: "auto", lastEdit: "auto-generated" },
];

const NAV = [
  { section: "Workspace", items: [
    { id: "dashboard", label: "Dashboard", icon: "grid" },
    { id: "tenders", label: "Tenders", icon: "file", count: 14 },
    { id: "upload", label: "Upload Tender", icon: "upload" },
    { id: "analysis", label: "Tender Analysis", icon: "scan", badge: "AI" },
    { id: "chat", label: "AI Assistant", icon: "spark", badge: "AI" },
  ]},
  { section: "Proposals", items: [
    { id: "builder", label: "Proposal Builder", icon: "edit" },
    { id: "compliance", label: "Compliance", icon: "shield", count: 3 },
    { id: "vault", label: "Document Vault", icon: "vault" },
  ]},
  { section: "Insights", items: [
    { id: "analytics", label: "Analytics", icon: "chart" },
    { id: "profile", label: "Company Profile", icon: "building" },
  ]},
  { section: "Account", items: [
    { id: "pricing", label: "Pricing", icon: "tag" },
    { id: "admin", label: "Admin", icon: "settings" },
  ]},
];

Object.assign(window, {
  TENDERS, COMPLIANCE_DOCS, ACTIVITY, CHAT_HISTORY,
  TENDER_REQUIREMENTS, EVAL_CRITERIA, TENDER_ACTIVITY_MONTH,
  PROPOSAL_SECTIONS, NAV,
});
