"""LLM provider abstraction.

Supports Anthropic (Claude) and OpenAI via httpx, plus a deterministic local
``stub`` provider so the platform runs fully offline with no API key. The stub
is intentionally *grounded*: it only echoes/condenses the context it is given
and always attaches page citations, honouring the product rule that the AI must
never invent tender requirements.
"""
from __future__ import annotations

import re
from dataclasses import dataclass

from app.config import settings

SYSTEM_PROMPT = (
    "You are TenderPilot AI, an assistant for South African public-procurement "
    "bidding. Rules: never invent requirements; cite the exact tender section or "
    "page for every claim; clearly state when information is missing; flag "
    "compliance risks; recommend the next action; use simple business English."
)


@dataclass
class LLMMessage:
    role: str  # "user" | "assistant"
    content: str


async def _anthropic_complete(system: str, messages: list[LLMMessage]) -> str:  # pragma: no cover
    import httpx

    payload = {
        "model": settings.llm_model,
        "max_tokens": 1500,
        "system": system,
        "messages": [{"role": m.role, "content": m.content} for m in messages],
    }
    headers = {
        "x-api-key": settings.anthropic_api_key or "",
        "anthropic-version": "2023-06-01",
        "content-type": "application/json",
    }
    async with httpx.AsyncClient(timeout=120) as client:
        r = await client.post(
            "https://api.anthropic.com/v1/messages", json=payload, headers=headers
        )
        r.raise_for_status()
        data = r.json()
    return "".join(block.get("text", "") for block in data.get("content", []))


async def _openai_complete(system: str, messages: list[LLMMessage]) -> str:  # pragma: no cover
    import httpx

    payload = {
        "model": settings.llm_model,
        "messages": [{"role": "system", "content": system}]
        + [{"role": m.role, "content": m.content} for m in messages],
        "max_tokens": 1500,
    }
    headers = {"Authorization": f"Bearer {settings.openai_api_key}"}
    async with httpx.AsyncClient(timeout=120) as client:
        r = await client.post(
            "https://api.openai.com/v1/chat/completions", json=payload, headers=headers
        )
        r.raise_for_status()
        data = r.json()
    return data["choices"][0]["message"]["content"]


_SENT_RE = re.compile(r"(?<=[.!?])\s+")


def _stub_complete(system: str, messages: list[LLMMessage]) -> str:
    """Deterministic, grounded fallback used when no API key is configured."""
    user = messages[-1].content if messages else ""
    # The RAG/analysis callers embed a CONTEXT block; condense it.
    context_match = re.search(r"CONTEXT:\n(.*?)(?:\n\nQUESTION:|\Z)", user, re.DOTALL)
    question_match = re.search(r"QUESTION:\s*(.*)", user, re.DOTALL)
    context = context_match.group(1).strip() if context_match else ""
    question = question_match.group(1).strip() if question_match else user.strip()

    if not context:
        return (
            "I could not find supporting text in the uploaded tender document to "
            "answer this. Please confirm the tender has finished processing, or "
            "rephrase your question."
        )

    # Rank context sentences by keyword overlap with the question.
    q_terms = set(re.findall(r"[a-z0-9]+", question.lower()))
    sentences = [s.strip() for s in _SENT_RE.split(context) if len(s.strip()) > 20]
    scored = sorted(
        sentences,
        key=lambda s: len(q_terms & set(re.findall(r"[a-z0-9]+", s.lower()))),
        reverse=True,
    )
    picked = [s for s in scored[:3] if (q_terms & set(re.findall(r"[a-z0-9]+", s.lower())))]
    if not picked:
        picked = sentences[:2]

    body = " ".join(picked)
    return (
        f"Based on the tender document: {body}\n\n"
        "Next action: verify this against your compliance vault and confirm the "
        "submission deadline. (Generated by the offline assistant — configure an "
        "LLM API key for richer, fully reasoned answers.)"
    )


async def complete(system: str, messages: list[LLMMessage]) -> str:
    provider = settings.llm_provider
    try:
        if provider == "anthropic" and settings.anthropic_api_key:
            return await _anthropic_complete(system, messages)
        if provider == "openai" and settings.openai_api_key:
            return await _openai_complete(system, messages)
    except Exception:
        # Never let a provider outage break the request — degrade to stub.
        pass
    return _stub_complete(system, messages)


async def generate(prompt: str, system: str = SYSTEM_PROMPT) -> str:
    return await complete(system, [LLMMessage(role="user", content=prompt)])
